import laspy
import numpy as np
import open3d as o3d
import os
import json
import pyproj


PCD_PATH = "/home/ros2_ws/outputs/georef_sam-qn_finished.pcd" 
JSON_PATH = "/home/ros2_ws/outputs/origin_metadata.json"
OUTPUT_LAS = "/home/ros2_ws/outputs/final_georef_map.las"

def convert():
    # 1. Load the metadata generated by the Data Extractor
    if not os.path.exists(JSON_PATH):
        print(f"CRITICAL ERROR: Metadata file not found at {JSON_PATH}")
        print("Make sure your ROS 2 script successfully wrote the JSON file!")
        return
    
    with open(JSON_PATH, "r") as f:
        meta = json.load(f)
        off_x = meta["offset_easting"]   # Easting
        off_y = meta["offset_northing"]  # Northing
        off_z = meta["offset_altitude"]  # Altitude
        epsg = meta.get("epsg", "3879")

    # 2. Load the georeferenced PCD from FlexCloud
    if not os.path.exists(PCD_PATH):
        print(f"ERROR: Point cloud not found at {PCD_PATH}")
        return

    print(f"--- Processing: {os.path.basename(PCD_PATH)} ---")
    pcd = o3d.io.read_point_cloud(PCD_PATH)
    points = np.asarray(pcd.points)
    
    # Check if intensity exists in the PCD
    intensities = None
    if pcd.has_colors():
        # Open3D maps intensity to RGB if it's a grayscale PCD
        intensities = np.asarray(pcd.colors)[:, 0] * 255 

    # 3. Setup LAS 1.4 Header
    # Point format 3 includes GPS time and Color/Intensity
    header = laspy.LasHeader(point_format=3, version="1.4")
    crs = pyproj.CRS.from_user_input(epsg)
    header.add_crs(crs)    
    
    # Set the Global Offset and Scale (0.001 = Millimeter precision)
    header.offsets = [off_x, off_y, off_z]
    header.scales = [0.001, 0.001, 0.001]

    # 4. Create the LAS object
    las = laspy.LasData(header)
    
    # Apply the global offsets and map the coordinates
    las.x = points[:, 1] + off_x
    las.y = points[:, 0] + off_y
    las.z = points[:, 2] + off_z

    if intensities is not None:
        las.intensity = intensities.astype(np.uint16)

    # 5. Save the uncompressed file
    print(f"Writing to: {OUTPUT_LAS}")
    print(f"Target Location: EPSG:{epsg}")
    las.write(OUTPUT_LAS)
    
    print("\n--- DONE ---")
    print(f"File size: {os.path.getsize(OUTPUT_LAS) / 1024**2:.2f} MB")

if __name__ == "__main__":
    convert()